### ISSUE TITLE
Front-end wed Development to be Completed

### ISSUE THREAD

**Issue by Samuel-Lindsey** [Samuel-Lindsey/Code_Lou_CW#2]
## TODO

*Courses left to complete the Front-end Web Development Track*

- [ ] GitHub Basics
- [ ] HTML Tables
- [ ] HTML Video & Audio
- [ ] Responsive Layouts
- [ ] AJAX Basics
- [ ] Bootstrap Basics
- [ ] Networking event one
- [ ] Networking event two
- [ ] Asana Questions and Path
- [ ] Final Project
